### ISSUE TITLE
ConnectTimeoutException while Uploading pages

### ISSUE THREAD

**Issue by dgautier** [zeldigas/text2confl#102]
I'm getting timeout exception and can't find where it's coming from, it happens after a few pages update so maybe the server is hanging but with this stacktrace it's quite hard to defined : 

io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://confluence.fake/rest/api/content?spaceKey=TEX&title=Component+058+-+title&expand=metadata.labels%2Cmetadata.properties.contenthash%2Cmetadata.properties.editor%2Cmetadata.properties.t2ctenant%2Cversion%2Cchildren.attachment%2Cancestors%2Cbody.storage, connect_timeout=unknown ms]
	at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:213)
	at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:210)
	at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:268)
	at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:257)
	at io.ktor.client.engine.cio.Endpoint.access$connect(Endpoint.kt:25)
	at io.ktor.client.engine.cio.Endpoint$connect$1.invokeSuspend(Endpoint.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by zeldigas** [comment]
I'll add customizable timeouts to ease further Troubleshooting

**Comment by zeldigas** [comment]
@dgautier added ability to customize request timeouts and enable http logging. please give it a try.

Cli can be found here: https://github.com/zeldigas/text2confl/actions/runs/6441969381?pr=105. Or use `latest` docker tag

**Comment by dgautier** [comment]
Hi, 

I've set a timeout to 30 000 and still sometime gets timeout exception. 

When i do activate Info logs on requests, i don't get them anymore. Probably cause the logging process slows down every calls.

Not really sure how i could set it up to be reliable. If you have any ideas ?

**Comment by zeldigas** [comment]
Two thoughts:

1. This might be related to amount of concurrent requests. In this case limiting concurrency might help
2. Might be related to http client used, in this case switching to something else like netty or native Java client might be the answer.

Let me create to builds for you to test both hypothesis
